/**
 * Problem: 3304. Find the K-th Character in String Game I
 *
 * Difficulty: Easy
 *
 * Language: JavaScript
 *
 * Performance: Runtime - 0 ms (Beats 100%)
 */

/**
 * Find the k-th character in a sequence generated by a specific pattern
 *
 * @param {number} k - 1-indexed position
 *
 * @returns {string} - k-th character in sequence
 */
const kthCharacter = (k) => {
  // Track character offset from 'a'
  let characterOffset = 0

  while (k !== 1) {
    // Find the highest power of 2 less than or equal to k
    let powerOfTwo = 31 - Math.clz32(k)

    // Adjust if k is exactly a power of 2
    if (1 << powerOfTwo === k) powerOfTwo--

    // Reduce k by the power of 2 and increment offset
    k -= 1 << powerOfTwo
    characterOffset++
  }

  // Convert offset to corresponding character
  return String.fromCharCode('a'.charCodeAt(0) + characterOffset)
}
